import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import { logger } from "../utils/logger.js";

const CONFIG_FILENAME = "contribot.toml";

/**
 * Fetch this week's GitHub trending repos.
 * Uses the unofficial GitHub trending page parsed via gh CLI search.
 */
export async function fetchTrendingRepos(limit = 10): Promise<string[]> {
  const { runGh } = await import("../utils/subprocess.js");

  // Use gh search to find trending repos (stars gained this week)
  const result = await runGh([
    "search", "repos",
    "--sort", "stars",
    "--order", "desc",
    "--created", `>${getDateWeekAgo()}`,
    "--json", "fullName",
    "--limit", String(limit),
  ]);

  if (result.exitCode === 0 && result.stdout.trim()) {
    try {
      const repos = JSON.parse(result.stdout) as Array<{ fullName: string }>;
      if (repos.length > 0) {
        return repos.map((r) => r.fullName);
      }
    } catch { /* fall through */ }
  }

  // Fallback: search most-starred repos updated this week
  const fallback = await runGh([
    "search", "repos",
    "--sort", "stars",
    "--order", "desc",
    "--language", "python,typescript,javascript,go,rust",
    "--updated", `>${getDateWeekAgo()}`,
    "--stars", ">500",
    "--json", "fullName",
    "--limit", String(limit),
  ]);

  if (fallback.exitCode === 0 && fallback.stdout.trim()) {
    try {
      const repos = JSON.parse(fallback.stdout) as Array<{ fullName: string }>;
      return repos.map((r) => r.fullName);
    } catch { /* fall through */ }
  }

  return [];
}

function getDateWeekAgo(): string {
  const d = new Date();
  d.setDate(d.getDate() - 7);
  return d.toISOString().split("T")[0];
}

/**
 * Generate a contribot.toml targeting the given repos.
 */
export function generateQuickstartConfig(
  repos: string[],
  opts: { apiKey?: string; baseUrl?: string; model?: string } = {}
): string {
  const model = opts.model || "sonnet";

  const repoBlocks = repos
    .map(
      (name) => `[[repos]]
name = "${name}"
focus = []
max_prs_per_day = 2
enabled = true`
    )
    .join("\n\n");

  return `# Contribot Configuration — generated by quickstart
# Target: GitHub trending repos (this week's top ${repos.length})

[general]
workspaces_dir = "./data/workspaces"
db_path = "./data/contribot.db"
log_dir = "./data/logs"
scan_interval_minutes = 120
max_concurrent_repos = 9
claude_model = "${model}"
max_budget_per_task_usd = 5
dashboard_port = 3847

[github]
username = ""

${repoBlocks}
`;
}

/**
 * Run the quickstart flow: fetch trending, generate config, optionally set API key.
 */
export async function runQuickstart(opts: {
  apiKey?: string;
  baseUrl?: string;
  model?: string;
}): Promise<void> {
  const configPath = resolve(process.cwd(), CONFIG_FILENAME);

  if (existsSync(configPath)) {
    console.log(`\n  contribot.toml already exists. Delete it first if you want to re-run quickstart.\n`);
    process.exitCode = 1;
    return;
  }

  // Set API key env if provided
  if (opts.apiKey) {
    process.env.ANTHROPIC_API_KEY = opts.apiKey;
    console.log("  ✓ API key set");
  }
  if (opts.baseUrl) {
    process.env.ANTHROPIC_BASE_URL = opts.baseUrl;
    console.log(`  ✓ Base URL set: ${opts.baseUrl}`);
  }

  console.log("\n  Fetching this week's GitHub trending repos...\n");

  const repos = await fetchTrendingRepos(10);

  if (repos.length === 0) {
    console.log("  ✗ Failed to fetch trending repos. Make sure `gh auth login` is done.\n");
    process.exitCode = 1;
    return;
  }

  console.log(`  Found ${repos.length} trending repos:`);
  for (const r of repos) {
    console.log(`    • ${r}`);
  }

  // Generate config
  const config = generateQuickstartConfig(repos, opts);
  writeFileSync(configPath, config, "utf-8");
  console.log(`\n  ✓ Generated contribot.toml with ${repos.length} repos`);
  console.log(`  ✓ Config saved to: ${configPath}\n`);
}
